---
categories:
  - labels:
      - feature
      - enhancement
    title: 🚀 Features
  - labels:
      - fix
      - bugfix
      - bug
    title: 🐛 Bug Fixes
  - label: chore
    title: 🧰 Maintenance
  - title: Minor
    type: version-resolver
    semver-increment: minor
    labels:
      - minor
  - title: Patch
    type: version-resolver
    semver-increment: patch
    labels:
      - patch
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: \<*_&
name-template: v$RESOLVED_VERSION 🌈
tag-template: v$RESOLVED_VERSION
template: "## Rifle, Rifle, Rifle!\n\n$CHANGES\n"
version-resolver:
  default: patch
  major:
    labels:
      - major
