---
name: Release Drafter
"on":
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - master
      - main
      - testing
concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: release-drafter/release-drafter@main
